// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAenMhuqvs8RZuVsqWQvvcaUEJF4OC0L1o',
    appId: '1:527607119267:web:89170d0d1bb074faf7ae16',
    messagingSenderId: '527607119267',
    projectId: 'socialmedia-12a0f',
    authDomain: 'socialmedia-12a0f.firebaseapp.com',
    databaseURL: 'https://socialmedia-12a0f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'socialmedia-12a0f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgM4YkZIEKnI1zOUe2OTKLJwzmW2Zuq2w',
    appId: '1:527607119267:android:2b0ecc9ef17da6c0f7ae16',
    messagingSenderId: '527607119267',
    projectId: 'socialmedia-12a0f',
    databaseURL: 'https://socialmedia-12a0f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'socialmedia-12a0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmzlbNBbynN99RGCsdGpOh2rpSu5b4xOA',
    appId: '1:527607119267:ios:9535d5e879a38bc5f7ae16',
    messagingSenderId: '527607119267',
    projectId: 'socialmedia-12a0f',
    databaseURL: 'https://socialmedia-12a0f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'socialmedia-12a0f.appspot.com',
    iosBundleId: 'com.example.socialwall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmzlbNBbynN99RGCsdGpOh2rpSu5b4xOA',
    appId: '1:527607119267:ios:5c2b1e4d6fd2a09bf7ae16',
    messagingSenderId: '527607119267',
    projectId: 'socialmedia-12a0f',
    databaseURL: 'https://socialmedia-12a0f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'socialmedia-12a0f.appspot.com',
    iosBundleId: 'com.example.socialwall.RunnerTests',
  );
}
